[build]
  base = "frontend"
  command = "npm ci && npm run build && npm ci --prefix netlify/functions" 
  publish = "dist"

[functions]
  directory = "netlify/functions"  
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
