[build]
  base    = "frontend"               # 빌드 실행 디렉터리
  command = "npm ci && npm run build"
  publish = "frontend/dist"          # Vite 결과물

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"           # 빠른 번들

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
