[build]
  # 함수 의존성까지 함께 설치 (플러그인 없이 안전)
  command = "npm ci && npm run build && npm ci --prefix netlify/functions"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA 리라이트만 남긴다 — Functions 규칙은 절대 추가하지 말 것
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
