[build]
  command = "npm ci && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# SPA 리라이트만 유지 (Functions 리다이렉트는 금지)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# 함수 의존성 자동 설치 플러그인
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
